//
//  ShowGifWorker.swift
//  GiphyApp
//
//  Created by Shishir Ahmed on 1/6/24.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ShowGifWorker {
    func doSomeWork() {
    }
}
