//
//  ListGifsWorker.swift
//  GiphyApp
//
//  Created by Shishir Ahmed on 1/6/24.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FLAnimatedImage

class ListGifsWorker {
    // MARK: Property
    
    let gifAPI: GiphyAPIProtocol = APIService()
    
    // MARK: Worker methods
    
    func searchGif(phrase: String, completion: @escaping ([Gif], Error?) -> Void) {
        gifAPI.searchGifs(phrase: phrase) { gifs, error in
            completion(gifs, error)
        }
    }
    
    func fetchTrendingGifs(completion: @escaping ([Gif], Error?) -> Void) {
        gifAPI.fetchTrendingGifs { gifs, error in
            completion(gifs, error)
        }
    }
    
    func fetchImagesData(urls: [String], completion: @escaping ([Data], Error?) -> Void) {
        gifAPI.fetchImagesData(urls: urls) { imagesData, error in
            completion(imagesData, error)
        }
    }
}
